import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'situs_rekomendasi.dart';
import 'dart:io';
import 'dart:async';

void main() {
  runApp(const MyApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: ListView(children: [
          Login(),
        ]),
      ),
    );
  }
}

class Login extends StatefulWidget {
  const Login({super.key});

  @override
  State<Login> createState() => _LoginState();
}

class _LoginState extends State<Login> {
  TextEditingController nameController = TextEditingController();
  TextEditingController passwordController = TextEditingController();
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          height: 815,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 97,
                top: 770,
                child: Container(
                  width: 220,
                  height: 19,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          'Don’t have an account ? ',
                          style: TextStyle(
                            color: Color(0xFF999EA1),
                            fontSize: 14,
                            fontFamily: 'Manrope',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 168,
                        top: 0,
                        child: Text(
                          'Sign Up',
                          style: TextStyle(
                            color: Color(0xFF4E0189),
                            fontSize: 14,
                            fontFamily: 'Manrope',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 125,
                child: Text(
                  'Hello again, you’ve been missed!',
                  style: TextStyle(
                    color: Color(0xFF999EA1),
                    fontSize: 14,
                    fontFamily: 'Manrope',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 92,
                child: Text(
                  'Hi, Wecome Back! 👋',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 25,
                    fontFamily: 'Manrope',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 196,
                child: Container(
                  width: 359,
                  height: 67,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          'Email',
                          style: TextStyle(
                            color: Color(0xFF4E0189),
                            fontSize: 14,
                            fontFamily: 'Manrope',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 26,
                        child: SizedBox(
                          width: 359,
                          height: 40,
                          child: TextField(
                            cursorColor: Color(0xFF4E0189),
                            controller: nameController,
                            textAlignVertical: TextAlignVertical.top,
                            style: TextStyle(
                              color: Colors.black,
                            ),
                            decoration: InputDecoration(
                                focusedBorder: OutlineInputBorder(
                                  borderSide: BorderSide(width: 1, color: Color(0xFFC5C5C5)),
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                enabledBorder: OutlineInputBorder(
                                  borderSide: BorderSide(width: 1, color: Color(0xFFC5C5C5)),
                                  borderRadius: BorderRadius.circular(10),
                                )
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 275,
                child: Container(
                  width: 359,
                  height: 67,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          'Password',
                          style: TextStyle(
                            color: Color(0xFF4E0189),
                            fontSize: 14,
                            fontFamily: 'Manrope',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 26,
                        child: SizedBox(
                          width: 359,
                          height: 40,
                          child: TextField(
                            cursorColor: Color(0xFF4E0189),
                            obscureText: true,
                            controller: passwordController,
                            textAlignVertical: TextAlignVertical.top,
                            style: TextStyle(
                              color: Colors.black,
                            ),
                            decoration: InputDecoration(
                                focusedBorder: OutlineInputBorder(
                                  borderSide: BorderSide(width: 1, color: Color(0xFFC5C5C5)),
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                enabledBorder: OutlineInputBorder(
                                  borderSide: BorderSide(width: 1, color: Color(0xFFC5C5C5)),
                                  borderRadius: BorderRadius.circular(10),
                                )
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 351,
                top: 313,
                child: Container(
                  width: 18,
                  height: 18,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                ),
              ),
              Positioned(
                left: 257,
                top: 360,
                child: Container(
                  width: 111,
                  height: 19,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          'Forgot Password',
                          style: TextStyle(
                            color: Color(0xFFFB344F),
                            fontSize: 14,
                            fontFamily: 'Manrope',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 406,
                child: Container(
                  width: 359,
                  height: 204,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 359,
                          height: 45,
                          decoration: ShapeDecoration(
                            color: Color(0xFF4E0189),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 108,
                        child: Container(
                          width: 173,
                          height: 45,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 173,
                                  height: 45,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Color(0xFFCDD1E0)),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 35,
                                top: 11,
                                child: Container(
                                  width: 82,
                                  height: 23,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 23,
                                          height: 23,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(
                                            children: [
                                              Image(
                                                  image: NetworkImage('https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/GitHub_Invertocat_Logo.svg/1200px-GitHub_Invertocat_Logo.svg.png')
                                              )
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 35,
                                        top: 3,
                                        child: Text(
                                          'GitHub',
                                          style: TextStyle(
                                            color: Color(0xFF242A31),
                                            fontSize: 14,
                                            fontFamily: 'Manrope',
                                            fontWeight: FontWeight.w600,
                                            height: 0,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 359,
                          height: 45,
                          child: ElevatedButton(
                              child: Text('Login'),
                              onPressed: () {
                                setState(() {
                                  _currentIndex = 0; // Change this based on the item's index
                                });
                                if (nameController.text == 'Basiz' && passwordController.text == 'basiz21') {
                                  const snackBar = SnackBar(
                                    content: Text('Berhasil Login'),
                                    duration: Duration(seconds: 2),
                                    backgroundColor: Colors.lightGreen,
                                  );
                                  ScaffoldMessenger.of(context).showSnackBar(snackBar);
                                  Navigator.push(
                                    context,
                                    MaterialPageRoute(builder: (context) => Beranda()
                                    ),
                                  );
                                }
                                else if (nameController.text != 'Basiz' && passwordController.text != 'basiz21') {
                                  const snackBar = SnackBar(
                                    content: Text('Username atau Password Anda Salah'),
                                    duration: Duration(seconds: 2),
                                    backgroundColor: Colors.redAccent,
                                  );
                                  ScaffoldMessenger.of(context).showSnackBar(snackBar);
                                };
                              },
                              style: ElevatedButton.styleFrom(
                                  primary: Color(0xFF4E0189), // Background color
                                  onPrimary: Colors.white,
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(10),
                                  )
                              )
                          ),
                        ),
                      ),
                      Positioned(
                        left: 186,
                        top: 108,
                        child: Container(
                          width: 173,
                          height: 45,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 173,
                                  height: 45,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Color(0xFFCDD1E0)),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 37,
                                top: 11,
                                child: Container(
                                  width: 80,
                                  height: 22.13,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 24,
                                          height: 22.13,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(
                                            children: [
                                              Image(
                                                  image: NetworkImage('https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png')
                                              ),
                                              Positioned(
                                                left: 0.02,
                                                top: 0.04,
                                                child: Container(
                                                  width: 23.98,
                                                  height: 22.09,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 36,
                                        top: 3,
                                        child: Text(
                                          'Google',
                                          style: TextStyle(
                                            color: Color(0xFF242A31),
                                            fontSize: 14,
                                            fontFamily: 'Manrope',
                                            fontWeight: FontWeight.w600,
                                            height: 0,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 67,
                        child: Container(
                          width: 359,
                          height: 19,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 154,
                                top: 0,
                                child: Text(
                                  'Or With',
                                  style: TextStyle(
                                    color: Color(0xFF999EA1),
                                    fontSize: 14,
                                    fontFamily: 'Manrope',
                                    fontWeight: FontWeight.w600,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: Container(
                                  width: 135,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 0.50,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 224,
                                top: 10,
                                child: Container(
                                  width: 135,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 0.50,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class Beranda extends StatefulWidget {
  @override
  _BerandaState createState() => _BerandaState();
}

class _BerandaState extends State<Beranda> {
  int _currentIndex = 0;
  final List<Widget> _screens = [
    Beranda(),
    Panduan(), // Add your PanduanAplikasi screen here
    // Add your Log Out screen here
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Beranda'),
        backgroundColor: Color(0xFF4E0189),
        foregroundColor: Colors.white ,
      ),
      body: Center(
        child: SizedBox(
          child: ListView(
            children: <Widget>[
              InkWell(
                borderRadius: BorderRadius.circular(30),
                onTap: () {
                  Navigator.push(context, MaterialPageRoute(builder: (context) => DataKelompok()));
                },
                child: Padding(
                  padding: const EdgeInsets.all(10.0),
                  child: Row(
                    children: [
                      Icon(
                        Icons.list_alt,
                        size: 70,
                      ),
                      Text(
                          'Daftar Anggota Kelompok',
                          style: TextStyle(
                            fontWeight: FontWeight.w300,
                            fontSize: 18,
                          ),
                          textAlign: TextAlign.center,
                      )
                    ],
                  ),
                ),
              ),
              InkWell(
                borderRadius: BorderRadius.circular(30),
                onTap: () {
                  Navigator.push(context, MaterialPageRoute(builder: (context) => StopwatchApp()));
                },
                child: Padding(
                  padding: const EdgeInsets.all(10.0),
                  child: Row(
                    children: [
                      Icon(
                        Icons.access_alarm,
                        size: 70,
                      ),
                      Text(
                        'Stopwatch',
                        style: TextStyle(
                            fontWeight: FontWeight.w300,
                            fontSize: 18
                        ),
                      )
                    ],
                  ),
                ),
              ),
              InkWell(
                borderRadius: BorderRadius.circular(30),
                onTap: () {
                  Navigator.push(context, MaterialPageRoute(builder: (context) => Rekomendasi()));
                },
                child: Padding(
                  padding: const EdgeInsets.all(10.0),
                  child: Row(
                    children: [
                      Icon(
                        Icons.thumb_up_alt_outlined,
                        size: 70,
                      ),
                      Text(
                        'Situs Rekomendasi',
                        style: TextStyle(
                            fontWeight: FontWeight.w300,
                            fontSize: 18
                        ),
                        textAlign: TextAlign.center,
                      )
                    ],
                  ),
                ),
              ),
              InkWell(
                borderRadius: BorderRadius.circular(30),
                onTap: () {
                  Navigator.push(context, MaterialPageRoute(builder: (context) => Favorit()));
                },
                child: Padding(
                  padding: const EdgeInsets.all(10.0),
                  child: Row(
                    children: [
                      Icon(
                        Icons.bookmark_added_outlined,
                        size: 70,
                      ),
                      Text(
                        'Favorit',
                        style: TextStyle(
                            fontWeight: FontWeight.w300,
                            fontSize: 18
                        ),
                      )
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        selectedItemColor: Color(0xFF4E0189),
        currentIndex: _currentIndex,
        onTap: (index) {
          if (index == 1) {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => Panduan()),
            );
          }
          if (index == 2) {
            _showLogoutDialog(context);
          } else {
            setState(() {
              _currentIndex = index;
            });
          }
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Beranda',
            backgroundColor: Color(0xFF4E0189)
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.menu_book_rounded),
            label: 'Panduan Aplikasi',
            backgroundColor: Color(0xFF4E0189)
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.logout),
            label: 'Log Out',
            backgroundColor: Color(0xFF4E0189)
          ),
        ],
      ),
    );
  }
  void _showLogoutDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Logout'),
          content: Text('Are you sure you want to log out?'),
          actions: <Widget>[
            TextButton(
              child: Text('Cancel'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
            TextButton(
              child: Text('Logout'),
              onPressed: () {
                // Perform logout actions here
                // For example, navigate to login screen or clear user data
                // Navigate to the login screen
                Navigator.of(context).pop(); // Close the dialog
                // Add your logout logic here
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => MyApp()),
                );
              },
            ),
          ],
        );
      },
    );
  }
}

class DataKelompok extends StatelessWidget {
  void _launchURL(String url) async {
    try {
      if (await canLaunch(url)) {
        await launch(url);
      } else {
        throw 'Could not launch $url';
      }
    } catch (error) {
      print('Error launching URL: $error');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Anggota Kelompok"),
        backgroundColor: Color(0xFF4E0189),
        foregroundColor: Colors.white,
      ),
      body: Column(
        children: [
          Container(
            child:
            InkWell(
              onTap: () => _launchURL('https://www.instagram.com/siddiqial_/'),
              child: ListTile(
                leading: CircleAvatar(
                  child: Text('S'),
                  backgroundColor: Color(0xFF4E0189),
                  foregroundColor: Colors.white,
                ),
                title: Text('Siddiqi Albiruny 124210003'),
              ),
            ),
          ),
          InkWell(
            onTap: () => _launchURL('https://www.instagram.com/ridho_contrisha/'),
            child: ListTile(
                leading: CircleAvatar(
                  child: Text('R'),
                  backgroundColor: Color(0xFF4E0189),
                  foregroundColor: Colors.white,
                ),
                title: Text('Ridho Contrisha 124210022')),
          ),
          InkWell(
            onTap: () => _launchURL('https://www.instagram.com/carlosngln/'),
            child: ListTile(
                leading: CircleAvatar(
                  child: Text('C'),
                  backgroundColor: Color(0xFF4E0189),
                  foregroundColor: Colors.white,
                ),
                title: Text('Carlos Nainggolan 124210045')
            ),
          ),
        ],
      ),
    );
  }
}

class StopwatchApp extends StatefulWidget {
  @override
  _StopwatchApp createState() => _StopwatchApp();
}

class _StopwatchApp extends State<StopwatchApp> {
  var _stopwatch = Stopwatch();
  var _isRunning = false;
  var _elapsedTime = Duration.zero;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Stopwatch'),
        backgroundColor: Color(0xFF4E0189),
        foregroundColor: Colors.white ,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              formatTime(_elapsedTime),
              style: TextStyle(fontSize: 48.0),
            ),
            SizedBox(height: 20.0),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                ElevatedButton(
                  onPressed: () {
                      if (_isRunning) {
                        _stopwatch.stop();
                      } else {
                        _stopwatch.start();
                        Timer.periodic(Duration(milliseconds: 100), _updateTime);
                      }
                      setState(() {
                        _isRunning = !_isRunning;
                      }
                    );
                  },
                  style: ElevatedButton.styleFrom(
                      primary: Color(0xFF4E0189), // Background color
                      onPrimary: Colors.white
                  ),
                  child: Text(_isRunning ? 'Stop' : 'Start'),
                ),
                SizedBox(width: 20.0),
                ElevatedButton(
                  onPressed: () {
                    if (!_isRunning) {
                      _stopwatch.reset();
                      setState(() {
                        _elapsedTime = Duration.zero;
                      });
                    }
                  },
                  style: ElevatedButton.styleFrom(
                      primary: Color(0xFF4E0189), // Background color
                      onPrimary: Colors.white
                  ),
                  child: Text('Reset'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  void _updateTime(Timer timer) {
    if (_stopwatch.isRunning) {
      setState(() {
        _elapsedTime = _stopwatch.elapsed;
      });
    }
  }

  String formatTime(Duration duration) {
    String minutes = (duration.inMinutes % 60).toString().padLeft(2, '0');
    String seconds = (duration.inSeconds % 60).toString().padLeft(2, '0');
    String milliseconds = (duration.inMilliseconds % 1000).toString().padLeft(3, '0').substring(0, 2);
    return '$minutes:$seconds.$milliseconds';
    }
}

class Rekomendasi extends StatefulWidget {
  @override
  _Rekomendasi createState() => _Rekomendasi();
}

class _Rekomendasi extends State<Rekomendasi> {

  void _launchURL(String url) async {
    try {
      if (await canLaunch(url)) {
        await launch(url);
      } else {
        throw 'Could not launch $url';
      }
    } catch (error) {
      print('Error launching URL: $error');
    }
  }

  void _toggleFavorite(int index) {
    setState(() {
      listSitus[index].isFavorite = !listSitus[index].isFavorite;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          automaticallyImplyLeading: true,
          leading: IconButton(
            icon: Icon(Icons.arrow_back),
            onPressed: () => Navigator.pop(context, false),
          ),
          title: Text('Situs Rekomendasi'),
          backgroundColor: Color(0xFF4E0189),
          foregroundColor: Colors.white ,
        ),
        body: ListView.builder(
          itemCount: listSitus.length,
          itemBuilder: (context, index) {
            return Padding(
              padding: const EdgeInsets.fromLTRB(5,8,0,0),
              child: ListTile(
                leading: CircleAvatar(
                    backgroundImage: NetworkImage(listSitus[index].image),
                    backgroundColor: Colors.transparent,
                ),
                title: InkWell(
                  onTap: () {
                    _launchURL(listSitus[index].siteUrl);
                  },
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        height: 60,
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(listSitus[index].name),
                            Text(
                              listSitus[index].siteUrl,
                              style: TextStyle(
                                fontStyle: FontStyle.italic,
                                color: Colors.grey,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                trailing: InkWell(
                  onTap: () {
                    _toggleFavorite(index); // Toggle favorite for the specific item
                    print('$index ${listSitus[index].isFavorite}');
                  },
                  child: Icon(
                    listSitus[index].isFavorite
                        ? Icons.bookmark
                        : Icons.bookmark_border,
                    color: Colors.yellow,
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

class Favorit extends StatelessWidget {
  final List<Situs> favoriteSitusList =
  listSitus.where((situs) => situs.isFavorite).toList();

  void _launchURL(String url) async {
    try {
      if (await canLaunch(url)) {
        await launch(url);
      } else {
        throw 'Could not launch $url';
      }
    } catch (error) {
      print('Error launching URL: $error');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Situs Favorit'),
        backgroundColor: Color(0xFF4E0189),
        foregroundColor: Colors.white,
      ),
      body: ListView.builder(
        itemCount: favoriteSitusList.length,
        itemBuilder: (context, index) {
          return Padding(
            padding: const EdgeInsets.fromLTRB(5,8,0,0),
            child: ListTile(
              leading: CircleAvatar(
                backgroundImage: NetworkImage(favoriteSitusList[index].image),
                backgroundColor: Colors.transparent,
              ),
              title: InkWell(
                onTap: () {
                  _launchURL(favoriteSitusList[index].siteUrl);
                },
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      height: 60,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(favoriteSitusList[index].name),
                          Text(
                            favoriteSitusList[index].siteUrl,
                            style: TextStyle(
                              fontStyle: FontStyle.italic,
                              color: Colors.grey,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}

class Panduan extends StatefulWidget {
  const Panduan({super.key});

  @override
  State<Panduan> createState() => _PanduanState();
}

class _PanduanState extends State<Panduan> {
  int _currentIndex = 1;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Panduan Penggunaan Aplikasi'),
        backgroundColor: Color(0xFF4E0189),
        foregroundColor: Colors.white,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ListView(
          children: [
            _buildStep('Login', [
              'Buka aplikasi dan Anda akan diarahkan ke halaman login.',
              'Masukkan kredensial login Anda (username dan password).',
              'Tekan tombol "Login" untuk masuk ke dalam aplikasi.'
            ]),
            _buildStep('Daftar Anggota Kelompok', [
              'Setelah login, Anda dapat mengakses menu "Daftar Anggota Kelompok".',
              'Pada halaman ini, Anda akan melihat daftar anggota kelompok yang telah terdaftar.',
              'Klik pada salah satu anggota kelompok untuk mengunjungi profil Instagram.',
            ]),
            _buildStep('Stopwatch', [
              'Menu "Stopwatch" memungkinkan Anda untuk menggunakan stopwatch.',
              'Pilih menu "Stopwatch" untuk membuka layar stopwatch.',
              'Tekan tombol "Start" untuk memulai penghitungan waktu, "Stop" untuk menghentikan sementara, dan "Reset" untuk mengulang penghitungan.'
            ]),
            _buildStep('Daftar Situs Rekomendasi', [
              'Pilih menu "Daftar Situs Rekomendasi" untuk melihat daftar situs yang direkomendasikan.',
              'Anda dapat menjelajahi berbagai situs yang mungkin bermanfaat dan klik pada situs tertentu untuk membuka halaman tersebut.'
              'Anda dapat menandai sebuah situs sebagai favorit dengan menekan tombol bookmark pada setiap item situs.',
              'Situs yang ditandai sebagai favorit akan tersimpan di sini untuk referensi cepat di masa mendatang.'

            ]),
            _buildStep('Daftar Situs Favorit', [
              'Pilih menu "Daftar Situs Favorit" untuk melihat daftar situs yang Anda tandai sebagai favorit.',
              'Situs yang ditandai sebagai favorit akan tersimpan di sini untuk referensi cepat di masa mendatang.'
              'Klik pada salah satu situs untuk membuka halaman situs.'
            ]),
            _buildStep('Logout', [
              'Untuk keluar dari aplikasi, Anda dapat menekan tombol "Logout" yang terdapat pada navigation bar.',
              'Pastikan untuk melakukan logout untuk menjaga keamanan akun Anda.'
            ]),
          ],
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        selectedItemColor: Color(0xFF4E0189),
        currentIndex: _currentIndex,
        onTap: (index) {
          if (index == 0) {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => Beranda()),
            );
          }
          else if (index == 2) {
            _showLogoutDialog(context);
          }
          else {
            setState(() {
              _currentIndex = index;
            });
          }
        },
        items: [
          BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Beranda',
              backgroundColor: Color(0xFF4E0189)
          ),
          BottomNavigationBarItem(
              icon: Icon(Icons.menu_book_rounded),
              label: 'Panduan Aplikasi',
              backgroundColor: Color(0xFF4E0189)
          ),
          BottomNavigationBarItem(
              icon: Icon(Icons.logout),
              label: 'Log Out',
              backgroundColor: Color(0xFF4E0189)
          ),
        ],
      ),
    );
  }

  void _showLogoutDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Logout'),
          content: Text('Are you sure you want to log out?'),
          actions: <Widget>[
            TextButton(
              child: Text('Cancel'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
            TextButton(
              child: Text('Logout'),
              onPressed: () {
                // Perform logout actions here
                // For example, navigate to login screen or clear user data
                // Navigate to the login screen
                Navigator.of(context).pop(); // Close the dialog
                // Add your logout logic here
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => MyApp()),
                );
              },
            ),
          ],
        );
      },
    );
  }

  Widget _buildStep(String title, List<String> steps) {
    return Card(
      elevation: 2.0,
      margin: const EdgeInsets.only(bottom: 16.0),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: TextStyle(fontSize: 18.0, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10.0),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: steps
                  .map((step) => Padding(
                padding: const EdgeInsets.only(bottom: 8.0),
                child: Text('- $step'),
              ))
                  .toList(),
            ),
          ],
        ),
      ),
    );
  }
}

class Page extends StatelessWidget {
  final String title;

  Page({required this.title});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(
        title,
        style: TextStyle(fontSize: 24.0),
      ),
    );
  }
}